---
title: "First Knit"
author: "LuisJovelPalacios"
output: 
  html_document:
    number_sections: true
    toc: true
    toc_depth: 5
date: "`r Sys.Date()`"   
---

# A Little Survey

Here are just a few questions so I can get to know you and so you can get practice submitting an assignment in Canvas.  For each question, insert your answer underneath. Make sure each answer is at the minimum a complete sentence with correctly spelled words and correct puncuation. 

## A short history of you.  
Where did you attend High School, and did you graduate? Compare english class to math, is one easier for you than the other? Finally which subject did you do the best in? Your answer should have at least two sentences devoted to each question.  
  
### my answer     
  I attended to palmdale high for my last 2 years of my high school career. And i did graduate from palmdale high a few months ago actually. yes i believe math is easier if im giving and example on how to do the work. but English in the other hand is a struggle for me mostly because i was taking English 101 instead of 12 grade English. I believe the subject I did the best on was Spanish because its my first language. so it was always easier for me because I already knew how to spell and read in it.


     


## Your computer and your and its capability?  
 For this class  you need a computer you can use at home.  So, what kind is it (windows, Apple, Linux)?  On a scale of 1 to 10, where 1 is a total dummy (doesn't know a mouse from a keyboard) and 10 is a complete geek (knows computer stuff in and out) How do you rate yourself?  You also need to have have internet access. How is your connection to the internet where you live?

### my answer   
  I have a windows at my house. And i say from a scale from 1-10 i am a good 7. I would say I have a good connection to the internet at my house.
   

## Others and You?   
What name do you prefer to be called by your classmates and instructor, if your buddys call you something but you want people in the class to call you something else - what would that be? 

### my answer     
 i would prefer to be called by my first name Luis by my classmates. I would like to be called Lu if i wanted people from the class to call me something eles.
   
 




## Aspirations?   
What do you want to achieve in life?  What college subject do you think would be of the greatest interest to you? What degree or certificate are you trying to achieve?

### my answer     
  what i want to achieve in life is being able to move and live in Germany one day. the college subject that really interest me is bio medical engineering. im trying to get at least a masters in Biomedical engineering.
   
 




## Past adventures?  
Have you ever gone to foreign countries, if so which ones, if not Where might you go in the future?  Have you ever been in the military, if so which branch, if not which branch would you choose if you got drafted, and why?

### my answer     
  I have gone to El Salvador i tend to go 2 times a year to vistit familly or just to go on vacation. i have never served in the millatery and i dont think i ever will. If i was to get drafted i guess i would like to join the air force because it more logic based.
   
  




## Why are you taking Statistics?  
Did you take Math 115 or Math 116 ?  Did you know Math 115 only satisfies a general education requirement but that Math 116 counts as taking statistics in several transfer institutions??  
What grade do you need to attain in stats to not upset your future plans, What is your plan?  
 

### my answer     
  i am currently in math 116 and i did not know that 115 did not actual give you credits im glad i choose 116. i think i need at least a B+ to not upset my future plans. Im planing on moving to Germany but a short term im hopping on going to UCLA to study.
   
 






  




